server:
  port: 8022

spring:
  application:
    name: cloud-mapper
  cloud:
    config:
      uri: http://localhost:8888
      name: mapper
      profile: dev

#  datasource:
#    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=utf-8
#    username: root
#    #    因为%算个特殊字符，若不加双引号注明字符串，则会报错
#    password: "%5QWERzxc"
#    driver-class-name: com.mysql.jdbc.Driver